stages:
  - build
  - deploy

image: docker:19.03.12

before_script:
  - docker login -u _json_key --password-stdin https://asia.gcr.io < $GCKEY_REGISTRY

.build:
  stage: build
  script:
    #- cp -f ${FILE_ENV} .env
    - docker build --cache-from asia.gcr.io/registry-334010/${NAME}-${BUILD_ENV}:latest -t asia.gcr.io/registry-334010/${NAME}-${BUILD_ENV}:latest -t asia.gcr.io/registry-334010/${NAME}-${BUILD_ENV}:${CI_COMMIT_SHORT_SHA} .
    - docker push asia.gcr.io/registry-334010/${NAME}-${BUILD_ENV}:${CI_COMMIT_SHORT_SHA}
    - docker push asia.gcr.io/registry-334010/${NAME}-${BUILD_ENV}:latest

.deploy:
  stage: deploy
  script:
    - |
      if [ "$(docker ps -a | grep ${NAME}-${BUILD_ENV})" ]; then
        docker rm --force ${NAME}-${BUILD_ENV}
      fi
    - docker run -d --name ${NAME}-${BUILD_ENV} -p ${H_PORT}:${C_PORT} --restart always asia.gcr.io/registry-334010/${NAME}-${BUILD_ENV}:latest

build-dev:
  extends: .build
  tags:
    - lrt-runner-dind2
  only:
    - dev
  variables:
    NAME: minhlong-admin-panel
    BUILD_ENV: dev
  #before_script:

deploy-dev:
  extends: .deploy
  tags:
    - lrt-runner-dind2
  only:
    - dev
  variables:
    NAME: minhlong-admin-panel
    BUILD_ENV: dev
    C_PORT: 3000 
    H_PORT: 3082


build-staging:
  extends: .build
  tags:
    - lrt-runner-dind2
  only:
    - staging
  variables:
    NAME: minhlong-admin-panel
    BUILD_ENV: staging
  #before_script:

deploy-staging:
  extends: .deploy
  tags:
    - lrt-runner-dind2
  only:
    - staging
  variables:
    NAME: minhlong-admin-panel
    BUILD_ENV: staging
    C_PORT: 3000 
    H_PORT: 3083

